import type { Property, User, Inquiry } from "@/types";

export const mockUser: User = {
  id: "user-1",
  name: "Sarah Mitchell",
  email: "sarah.mitchell@example.com",
  avatar: "https://picsum.photos/seed/sarah-mitchell/200/200",
  createdAt: "2024-11-03T09:15:00.000Z",
};

function images(seed: string, count: number): string[] {
  return Array.from(
    { length: count },
    (_, i) => `https://picsum.photos/seed/${seed}-${i + 1}/1200/800`,
  );
}

export const mockProperties: Property[] = [
  {
    id: "prop-1",
    title: "Modern Downtown Apartment",
    description:
      "A bright, open-plan apartment in the heart of downtown, walking distance to restaurants, transit, and shopping. Floor-to-ceiling windows fill the space with natural light.",
    propertyType: "apartment",
    listingType: "buy",
    price: 385000,
    currency: "USD",
    location: "Downtown, Austin",
    address: "142 Congress Ave, Austin, TX",
    bedrooms: 2,
    bathrooms: 2,
    size: 95,
    amenities: ["parking", "elevator", "air conditioning", "security"],
    images: images("prop1", 4),
    ownerId: "user-1",
    createdAt: "2025-06-01T10:00:00.000Z",
  },
  {
    id: "prop-2",
    title: "Sunny Suburban Family House",
    description:
      "A spacious four-bedroom house with a large backyard, perfect for families. Located in a quiet, tree-lined neighborhood close to top-rated schools.",
    propertyType: "house",
    listingType: "buy",
    price: 620000,
    currency: "USD",
    location: "Maple Grove, Austin",
    address: "27 Maple Grove Rd, Austin, TX",
    bedrooms: 4,
    bathrooms: 3,
    size: 210,
    amenities: ["parking", "garden", "balcony", "air conditioning"],
    images: images("prop2", 5),
    ownerId: "user-2",
    createdAt: "2025-05-18T10:00:00.000Z",
  },
  {
    id: "prop-3",
    title: "Luxury Villa with Private Pool",
    description:
      "An elegant villa featuring a private pool, landscaped garden, and panoramic hill views. Ideal for those seeking privacy and comfort.",
    propertyType: "villa",
    listingType: "buy",
    price: 1250000,
    currency: "USD",
    location: "Hill Country, Austin",
    address: "8 Overlook Dr, Austin, TX",
    bedrooms: 5,
    bathrooms: 4,
    size: 380,
    amenities: ["pool", "garden", "parking", "security", "furnished"],
    images: images("prop3", 6),
    ownerId: "user-1",
    createdAt: "2025-04-22T10:00:00.000Z",
  },
  {
    id: "prop-4",
    title: "Cozy Studio Near Campus",
    description:
      "A compact, well-designed studio ideal for students or young professionals. Just a five-minute walk to the university.",
    propertyType: "apartment",
    listingType: "rent",
    price: 950,
    currency: "USD",
    location: "West Campus, Austin",
    address: "310 Guadalupe St, Austin, TX",
    bedrooms: 1,
    bathrooms: 1,
    size: 42,
    amenities: ["elevator", "air conditioning", "furnished"],
    images: images("prop4", 3),
    ownerId: "user-3",
    createdAt: "2025-06-10T10:00:00.000Z",
  },
  {
    id: "prop-5",
    title: "Spacious 3-Bedroom Rental",
    description:
      "A comfortable, family-friendly apartment with a large living area, in-unit laundry, and a private balcony overlooking the park.",
    propertyType: "apartment",
    listingType: "rent",
    price: 1800,
    currency: "USD",
    location: "Zilker, Austin",
    address: "55 Barton Springs Rd, Austin, TX",
    bedrooms: 3,
    bathrooms: 2,
    size: 130,
    amenities: ["parking", "balcony", "elevator", "air conditioning"],
    images: images("prop5", 4),
    ownerId: "user-1",
    createdAt: "2025-05-30T10:00:00.000Z",
  },
  {
    id: "prop-6",
    title: "Charming Cottage House",
    description:
      "A charming two-bedroom cottage with a private garden, recently renovated kitchen, and a cozy fireplace for cooler evenings.",
    propertyType: "house",
    listingType: "rent",
    price: 2100,
    currency: "USD",
    location: "Travis Heights, Austin",
    address: "19 Live Oak St, Austin, TX",
    bedrooms: 2,
    bathrooms: 1,
    size: 88,
    amenities: ["garden", "parking", "furnished"],
    images: images("prop6", 4),
    ownerId: "user-2",
    createdAt: "2025-03-14T10:00:00.000Z",
  },
  {
    id: "prop-7",
    title: "Prime Commercial Office Space",
    description:
      "A modern office suite in a prestigious business tower, featuring open-plan workspace, meeting rooms, and 24/7 building security.",
    propertyType: "office",
    listingType: "rent",
    price: 4200,
    currency: "USD",
    location: "Financial District, Austin",
    address: "500 Congress Ave, Austin, TX",
    bedrooms: 0,
    bathrooms: 2,
    size: 260,
    amenities: ["parking", "elevator", "security", "air conditioning"],
    images: images("prop7", 4),
    ownerId: "user-3",
    createdAt: "2025-06-15T10:00:00.000Z",
  },
  {
    id: "prop-8",
    title: "Retail Shop on Main Street",
    description:
      "A high-visibility retail unit on a busy shopping street, with large storefront windows and a flexible open layout.",
    propertyType: "shop",
    listingType: "buy",
    price: 340000,
    currency: "USD",
    location: "South Congress, Austin",
    address: "1400 S Congress Ave, Austin, TX",
    bedrooms: 0,
    bathrooms: 1,
    size: 110,
    amenities: ["security", "air conditioning"],
    images: images("prop8", 3),
    ownerId: "user-2",
    createdAt: "2025-02-27T10:00:00.000Z",
  },
  {
    id: "prop-9",
    title: "Development Land Plot",
    description:
      "A generous plot of undeveloped land, zoned for residential construction, with utilities available at the road.",
    propertyType: "land",
    listingType: "buy",
    price: 210000,
    currency: "USD",
    location: "Dripping Springs, Austin",
    address: "Ranch Rd 12, Dripping Springs, TX",
    bedrooms: 0,
    bathrooms: 0,
    size: 4000,
    amenities: [],
    images: images("prop9", 2),
    ownerId: "user-1",
    createdAt: "2025-01-20T10:00:00.000Z",
  },
  {
    id: "prop-10",
    title: "Elegant High-Rise Condo",
    description:
      "A sleek condo on the 22nd floor with sweeping city views, a private balcony, and access to a rooftop pool and gym.",
    propertyType: "apartment",
    listingType: "buy",
    price: 540000,
    currency: "USD",
    location: "Rainey Street, Austin",
    address: "70 Rainey St, Austin, TX",
    bedrooms: 2,
    bathrooms: 2,
    size: 105,
    amenities: ["pool", "elevator", "parking", "security", "balcony"],
    images: images("prop10", 5),
    ownerId: "user-3",
    createdAt: "2025-06-20T10:00:00.000Z",
  },
  {
    id: "prop-11",
    title: "Quiet 1-Bedroom Rental",
    description:
      "A peaceful one-bedroom unit with a private entrance, updated appliances, and a small patio, tucked away from the street.",
    propertyType: "apartment",
    listingType: "rent",
    price: 1250,
    currency: "USD",
    location: "Hyde Park, Austin",
    address: "45th St, Austin, TX",
    bedrooms: 1,
    bathrooms: 1,
    size: 60,
    amenities: ["parking", "air conditioning", "furnished"],
    images: images("prop11", 3),
    ownerId: "user-2",
    createdAt: "2025-04-05T10:00:00.000Z",
  },
  {
    id: "prop-12",
    title: "Countryside Villa Retreat",
    description:
      "A serene villa surrounded by open countryside, featuring a wraparound porch, guest house, and mature fruit orchard.",
    propertyType: "villa",
    listingType: "rent",
    price: 3600,
    currency: "USD",
    location: "Bee Cave, Austin",
    address: "12 Orchard Ln, Bee Cave, TX",
    bedrooms: 4,
    bathrooms: 3,
    size: 320,
    amenities: ["garden", "parking", "pool", "furnished"],
    images: images("prop12", 5),
    ownerId: "user-1",
    createdAt: "2025-05-02T10:00:00.000Z",
  },
  {
    id: "prop-13",
    title: "Affordable Starter House",
    description:
      "A well-maintained three-bedroom home, ideal for first-time buyers, with an updated bathroom and a fenced-in backyard.",
    propertyType: "house",
    listingType: "buy",
    price: 295000,
    currency: "USD",
    location: "Riverside, Austin",
    address: "8 Riverside Dr, Austin, TX",
    bedrooms: 3,
    bathrooms: 2,
    size: 140,
    amenities: ["garden", "parking"],
    images: images("prop13", 4),
    ownerId: "user-3",
    createdAt: "2025-03-29T10:00:00.000Z",
  },
  {
    id: "prop-14",
    title: "Boutique Office Loft",
    description:
      "A converted warehouse loft with exposed brick, high ceilings, and an open floor plan, perfect for a creative studio or small team.",
    propertyType: "office",
    listingType: "buy",
    price: 465000,
    currency: "USD",
    location: "East Austin, Austin",
    address: "220 E 6th St, Austin, TX",
    bedrooms: 0,
    bathrooms: 1,
    size: 180,
    amenities: ["elevator", "air conditioning", "security"],
    images: images("prop14", 3),
    ownerId: "user-2",
    createdAt: "2025-06-08T10:00:00.000Z",
  },
];

export const mockInquiries: Inquiry[] = [
  {
    id: "inq-1",
    propertyId: "prop-1",
    senderName: "James Carter",
    senderEmail: "james.carter@example.com",
    senderPhone: "+1 512-555-0142",
    message:
      "Hi, I'm interested in viewing this apartment this weekend. Is Saturday afternoon available?",
    createdAt: "2025-06-20T14:30:00.000Z",
  },
  {
    id: "inq-2",
    propertyId: "prop-3",
    senderName: "Emily Nguyen",
    senderEmail: "emily.nguyen@example.com",
    senderPhone: "+1 512-555-0198",
    message:
      "Could you share more details about the pool maintenance and HOA fees for this villa?",
    createdAt: "2025-06-22T09:05:00.000Z",
  },
  {
    id: "inq-3",
    propertyId: "prop-5",
    senderName: "Michael Ross",
    senderEmail: "michael.ross@example.com",
    message:
      "Is this rental still available for a September move-in? I'd also like to ask about pet policies.",
    createdAt: "2025-06-25T17:45:00.000Z",
  },
];
